/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IContract, IContractInterface } from "../../interfaces/IContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_bar",
        type: "uint256",
      },
    ],
    name: "aFunction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IContract__factory {
  static readonly abi = _abi;
  static createInterface(): IContractInterface {
    return new utils.Interface(_abi) as IContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContract {
    return new Contract(address, _abi, signerOrProvider) as IContract;
  }
}
